### PR TITLE
gl4: fix isinf minimum GLSL version

### PR DESCRIPTION
**Pull request by imirkin**
This function appeared in GLSL 1.30, like isnan.

### CODE REVIEW

**Comment by johnstiles-google** [comment]
@oddhack I just independently ran into this bug (see #109). Please consider accepting this PR.

**Comment by oddhack** [comment]
@pdaniell-nv please sign off - LGTM.

**Comment by johnstiles-google** [comment]
Thank you @pdaniell-nv and @oddhack !

**Comment by mattst88** [comment]
In the future, what do we need to do to get obviously correct fixes into the man pages? Immediately cc @pdaniell-nv and @oddhack?

Presumably could have saved John some headache if this had been merged in December.

**Comment by pdaniell-nv** [comment]
> In the future, what do we need to do to get obviously correct fixes into the man pages? Immediately cc @pdaniell-nv and @oddhack?

Sorry for the delay on this. Yes, please at ping us if you need faster attention.

**Pull request merged**
