### PR TITLE
Added missing GL_HALF_FLOAT

### LINKED ISSUE #42: gl4: glTexImage* functions miss GL_HALF_FLOAT as input for parameter `type`
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage1D.xhtml
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage3D.xhtml

I checked gl spec and as I read so far the half float type is allowed for transferring pixels. And in fact, the corresponding gles page (https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glTexImage2D.xhtml) has `GL_HALF_FLOAT` included for `type`, so I believe this is also allowed in opengl4.

### LINKED ISSUE #48: declaration typo in memoryBarrier man page
In  https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/memoryBarrier.xhtml
and https://www.khronos.org/registry/OpenGL-Refpages/es3/html/memoryBarrier.xhtml

the declaration of memoryBarrier() is incorrect. 

The return value really should be void, not uint, based on the GLSL specification.

### PR DESCRIPTION
**Pull request by Vallentin**
Fixes #42.

### CODE REVIEW

**Comment by oddhack** [comment]
This looks good, but is incomplete in that the "Version Support" section could be updated to mention when HALF_FLOAT support was introduced (GL 3.0). That's not essential but would be nice if you're willing to do it.

**Comment by Vallentin** [comment]
Just as a new entry to the table in "Version Support"? If so, sure.

On that note, how about similarly adding shader types to [glCreateShader](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCreateShader.xhtml)'s "Version Support" table?

**Comment by oddhack** [comment]
That would be a great addition, if you're up for it - thanks!

**Comment by Vallentin** [comment]
Sure thing. I'll add it later when I have a bit of time.

**Comment by Vallentin** [comment]
I've now added them as constants to all `glTexImage*` version support tables.

table

**Pull request merged**
